version: '3.8'

services:
  # MongoDB数据库
  mongodb:
    image: mongo:6.0
    container_name: franklin-virtues-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: franklin-virtues
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - franklin-network

  # Node.js应用
  app:
    build: .
    container_name: franklin-virtues-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3003
      MONGODB_URI: mongodb://admin:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017/franklin-virtues?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-franklin-virtues-secret-key-2024-change-this-in-production}
      JWT_EXPIRE: 7d
      BCRYPT_ROUNDS: 12
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    networks:
      - franklin-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: franklin-virtues-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - franklin-network

volumes:
  mongodb_data:
    driver: local

networks:
  franklin-network:
    driver: bridge